/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

// attachmentReadPdf.test.js — chat/tools/attachment_read_pdf.js: argument validation, attachment
// choice, size and type refusals, and the text returned to the model. PDFs are generated by
// test/helpers/pdfFixtures.js and parsed by the bundled pdf.js.

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { buildPdf } from './helpers/pdfFixtures.js';

vi.mock('../agent/modules/utils.js', () => ({
  log: vi.fn(),
  resolveUniqueMessageKey: vi.fn(async (id) => (id === 'acct:/INBOX:msg-1' ? { weFolder: 'acct:/INBOX', headerID: 'msg-1', weID: 101 } : null)),
}));

const tool = await import('../chat/tools/attachment_read_pdf.js');
const { CONFIG } = tool._testing;

const LIB_DIR = path.resolve(import.meta.dirname, '../chat/libs/pdfjs');
const pdfjs = await import(pathToFileURL(path.join(LIB_DIR, 'pdf.min.mjs')).href);
pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(path.join(LIB_DIR, 'pdf.worker.min.mjs')).href;
const cMapUrl = path.join(LIB_DIR, 'cmaps') + path.sep;

const UNIQUE_ID = 'acct:/INBOX:msg-1';
let deps;
let files;

const att = (name, contentType, partName, size = 1000) => ({ name, contentType, partName, size });

function setMessage(attachments, bytesByPart = {}) {
  files = bytesByPart;
  globalThis.browser = {
    messages: {
      listAttachments: vi.fn(async () => attachments),
      getAttachmentFile: vi.fn(async (_weID, partName) => {
        const bytes = files[partName];
        if (!bytes) throw new Error('no such part');
        return { arrayBuffer: async () => bytes.slice().buffer };
      }),
    },
  };
}

const read = (args = {}) => tool.run({ unique_id: UNIQUE_ID, ...args }, {}, deps);

beforeEach(() => {
  deps = { loadPdfjs: vi.fn(async () => pdfjs), cMapUrl: () => cMapUrl };
});

afterEach(() => {
  delete globalThis.browser;
  vi.useRealTimers();
});

describe('attachment_read_pdf — arguments', () => {
  beforeEach(() => setMessage([att('a.pdf', 'application/pdf', '1.2')], { '1.2': buildPdf({ pages: ['A'] }) }));

  it('requires a unique_id', async () => {
    expect(await tool.run({}, {}, deps)).toEqual({ error: 'invalid or missing unique_id' });
  });

  it.each([0, -1, 1.5, 'abc', '2x'])('rejects start_page %s before touching the message', async (value) => {
    expect(await read({ start_page: value })).toEqual({ error: 'start_page must be a whole number of 1 or more' });
    expect(browser.messages.listAttachments).not.toHaveBeenCalled();
  });

  it('rejects an invalid end_page, and one before start_page', async () => {
    expect(await read({ end_page: 0 })).toEqual({ error: 'end_page must be a whole number of 1 or more' });
    expect(await read({ start_page: 3, end_page: 2 })).toEqual({ error: 'end_page must not be before start_page' });
    expect(browser.messages.listAttachments).not.toHaveBeenCalled();
  });

  it('accepts page numbers sent as numeric strings', async () => {
    const out = await read({ start_page: '1', end_page: '1' });
    expect(out).toContain('pages_read: 1');
  });

  it('reports an id that does not resolve to one message', async () => {
    expect(await tool.run({ unique_id: 'acct:/INBOX:missing' }, {}, deps)).toEqual({ error: 'Invalid unique_id' });
  });
});

describe('attachment_read_pdf — choosing the attachment', () => {
  const pdfBytes = buildPdf({ pages: ['Chosen'] });

  it('reads the only PDF when no name is given, skipping non-PDF attachments', async () => {
    setMessage([att('photo.jpg', 'image/jpeg', '1.2'), att('Report.PDF', 'application/octet-stream', '1.3')], { '1.3': pdfBytes });
    const out = await read();
    expect(out).toContain('attachment: Report.PDF');
    expect(browser.messages.getAttachmentFile).toHaveBeenCalledWith(101, '1.3');
  });

  it('treats an application/pdf part without a .pdf name as a PDF', async () => {
    setMessage([att('scan', 'application/pdf; name=scan', '2')], { 2: pdfBytes });
    expect(await read()).toContain('attachment: scan');
  });

  it('asks for a name, listing them, when there are several PDFs', async () => {
    setMessage([att('a.pdf', 'application/pdf', '1.2'), att('b.pdf', 'application/pdf', '1.3')]);
    expect(await read()).toEqual({ error: 'this email has several PDF attachments; set attachment_name to one of: "a.pdf", "b.pdf"' });
    expect(browser.messages.getAttachmentFile).not.toHaveBeenCalled();
  });

  it('reads the named PDF among several', async () => {
    setMessage([att('a.pdf', 'application/pdf', '1.2'), att('b.pdf', 'application/pdf', '1.3')], { '1.3': pdfBytes });
    expect(await read({ attachment_name: 'b.pdf' })).toContain('attachment: b.pdf');
    expect(browser.messages.getAttachmentFile).toHaveBeenCalledWith(101, '1.3');
  });

  it('says when the email has no PDF attachments', async () => {
    setMessage([att('notes.txt', 'text/plain', '1.2')]);
    expect(await read()).toEqual({ error: 'this email has no PDF attachments' });
  });

  it('refuses a named attachment that is not a PDF', async () => {
    setMessage([att('notes.docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '1.2')]);
    expect(await read({ attachment_name: 'notes.docx' })).toEqual({ error: 'attachment "notes.docx" is not a PDF' });
    expect(browser.messages.getAttachmentFile).not.toHaveBeenCalled();
  });

  it('lists the PDFs when the named attachment does not exist', async () => {
    setMessage([att('a.pdf', 'application/pdf', '1.2')]);
    expect(await read({ attachment_name: 'missing.pdf' })).toEqual({ error: 'no attachment named "missing.pdf"; PDF attachments on this email: "a.pdf"' });
    setMessage([]);
    expect(await read({ attachment_name: 'missing.pdf' })).toEqual({ error: 'no attachment named "missing.pdf", and this email has no PDF attachments' });
  });

  it('refuses to guess between attachments that share a name', async () => {
    setMessage([att('same.pdf', 'application/pdf', '1.2'), att('same.pdf', 'application/pdf', '1.3')]);
    expect(await read({ attachment_name: 'same.pdf' })).toEqual({ error: 'this email has several attachments named "same.pdf", so this tool cannot tell which one to read' });
    expect(browser.messages.getAttachmentFile).not.toHaveBeenCalled();
  });

  it('reports a failure to list attachments', async () => {
    setMessage([]);
    browser.messages.listAttachments.mockRejectedValueOnce(new Error('offline'));
    expect(await read()).toEqual({ error: 'could not list the email\'s attachments' });
  });
});

describe('attachment_read_pdf — size, download and type', () => {
  it('refuses an attachment listed over the size limit without downloading it', async () => {
    setMessage([att('big.pdf', 'application/pdf', '1.2', 30 * 1024 * 1024)]);
    expect(await read()).toEqual({ error: 'the PDF is too large to read (30.0 MB; the limit is 25.0 MB)' });
    expect(browser.messages.getAttachmentFile).not.toHaveBeenCalled();
  });

  it('refuses downloaded bytes over the limit even when the listed size was small', async () => {
    const big = new Uint8Array(CONFIG.MAX_FILE_BYTES + 1);
    big.set(new TextEncoder().encode('%PDF-1.4'));
    setMessage([att('big.pdf', 'application/pdf', '1.2', 10)], { '1.2': big });
    expect((await read()).error).toMatch(/^the PDF is too large to read/);
    expect(deps.loadPdfjs).not.toHaveBeenCalled();
  });

  it('reports a failed download', async () => {
    setMessage([att('a.pdf', 'application/pdf', '1.2')], {});
    expect(await read()).toEqual({ error: 'could not download the attachment' });
  });

  it('refuses bytes that are not a PDF before loading the parser', async () => {
    setMessage([att('fake.pdf', 'application/pdf', '1.2')], { '1.2': new TextEncoder().encode('<html>not a pdf</html>') });
    expect(await read()).toEqual({ error: 'the file is not a readable PDF (it is damaged or not really a PDF)' });
    expect(deps.loadPdfjs).not.toHaveBeenCalled();
  });
});

describe('attachment_read_pdf — outcomes from the parser', () => {
  const withPdf = (bytes) => setMessage([att('doc.pdf', 'application/pdf', '1.2')], { '1.2': bytes });

  it('returns the header lines and each page\'s text, marking empty pages', async () => {
    withPdf(buildPdf({ pages: ['First page', null, 'Third page'] }));
    expect(await read()).toBe([
      `unique_id: ${UNIQUE_ID}`,
      'attachment: doc.pdf',
      'total_pages: 3',
      'pages_read: 1-3',
      'text:',
      '[page 1]',
      'First page',
      '[page 2]',
      '(no text on this page)',
      '[page 3]',
      'Third page',
    ].join('\n'));
  });

  it('gives next_start_page when more pages remain', async () => {
    withPdf(buildPdf({ pages: ['one', 'two', 'three'] }));
    const out = await read({ start_page: 2, end_page: 2 });
    expect(out).toContain('pages_read: 2\nnext_start_page: 3\n');
    expect(out).toContain('[page 2]\ntwo');
    expect(out).not.toContain('[page 3]');
  });

  it('reads at most MAX_PAGES_PER_CALL pages per call', async () => {
    const count = CONFIG.MAX_PAGES_PER_CALL + 2;
    withPdf(buildPdf({ pages: Array.from({ length: count }, (_, i) => `p${i + 1}`) }));
    const out = await read();
    expect(out).toContain(`pages_read: 1-${CONFIG.MAX_PAGES_PER_CALL}\nnext_start_page: ${CONFIG.MAX_PAGES_PER_CALL + 1}`);
  });

  it('says plainly when the pages have no text at all (a scanned PDF)', async () => {
    withPdf(buildPdf({ pages: [{ image: true }, { image: true }] }));
    expect(await read()).toContain('note: none of these pages has any text; the PDF is probably scanned images, and text recognition is not available');
  });

  it('does not call a PDF scanned when some page has text', async () => {
    withPdf(buildPdf({ pages: [{ image: true }, 'caption'] }));
    expect(await read()).not.toContain('scanned');
  });

  it('refuses a password-protected PDF', async () => {
    withPdf(buildPdf({ pages: ['secret'], encrypt: { userPassword: 'pw', ownerPassword: 'owner' } }));
    expect(await read()).toEqual({ error: 'the PDF is password-protected, so its text cannot be read' });
  });

  it('refuses a damaged PDF', async () => {
    withPdf(new TextEncoder().encode('%PDF-1.4 truncated nonsense'));
    expect(await read()).toEqual({ error: 'the file is not a readable PDF (it is damaged or not really a PDF)' });
  });

  it('reports a start_page past the end with the page count', async () => {
    withPdf(buildPdf({ pages: ['one', 'two'] }));
    expect(await read({ start_page: 3 })).toEqual({ error: 'start_page 3 is past the last page (the PDF has 2 pages)' });
  });

  it('stops a parse that runs past the deadline', async () => {
    withPdf(buildPdf({ pages: ['x'] }));
    const destroy = vi.fn(async () => {});
    deps.loadPdfjs = async () => ({ getDocument: () => ({ promise: new Promise(() => {}), destroy }) });
    vi.useFakeTimers();
    const pending = read();
    await vi.advanceTimersByTimeAsync(CONFIG.PARSE_TIMEOUT_MS);
    expect(await pending).toEqual({ error: 'reading the PDF took too long and was stopped' });
    expect(destroy).toHaveBeenCalled();
  });

  it('reports a parser that could not run at all', async () => {
    withPdf(buildPdf({ pages: ['x'] }));
    deps.loadPdfjs = async () => ({ getDocument: () => ({ promise: Promise.reject(new Error('worker failed')), destroy: async () => {} }) });
    expect(await read()).toEqual({ error: 'the PDF could not be read' });
  });

  it('notes a page cut at the output limit and one call stopped at it', async () => {
    const block = (ch, lines) => Array(lines).fill(ch.repeat(30)).join('\n');
    const original = CONFIG.MAX_OUTPUT_CHARS;
    CONFIG.MAX_OUTPUT_CHARS = 100;
    try {
      withPdf(buildPdf({ pages: [block('a', 5), 'tail'] }));
      const cut = await read();
      expect(cut).toContain(`note: page 1 is longer than one call can return; only its first 100 of ${block('a', 5).length} characters are shown`);
      expect(cut).toContain('next_start_page: 2');

      withPdf(buildPdf({ pages: [block('a', 2), block('b', 2), 'tail'] }));
      const stopped = await read();
      expect(stopped).toContain('note: stopped at the per-call text limit; continue with start_page 2');
      expect(stopped).not.toContain('[page 2]');
    } finally {
      CONFIG.MAX_OUTPUT_CHARS = original;
    }
  });
});

describe('attachment_read_pdf — registration in chat/tools/core.js', () => {
  // core.js pulls in the whole chat UI graph, so its registration is checked from source: the
  // backend offers the tool to 1.9.0+ clients, and an unregistered name answers "unknown tool".
  it('is imported, routed by name in TOOL_IMPL, and has its own activity label', async () => {
    const { readFile } = await import('node:fs/promises');
    const src = await readFile(path.resolve(import.meta.dirname, '../chat/tools/core.js'), 'utf8');
    const binding = src.match(/import \* as (\w+) from "\.\/attachment_read_pdf\.js";/)?.[1];
    expect(binding).toBeTruthy();
    const toolImpl = src.slice(src.indexOf('const TOOL_IMPL = {'), src.indexOf('};', src.indexOf('const TOOL_IMPL = {')));
    expect(toolImpl).toContain(`attachment_read_pdf: ${binding},`);
    expect(src).toContain('case "attachment_read_pdf": {');
  });
});

describe('attachment_read_pdf — parser load failure', () => {
  it('returns an error instead of throwing when pdf.js cannot be loaded', async () => {
    setMessage([att('a.pdf', 'application/pdf', '1.2')], { '1.2': buildPdf({ pages: ['A'] }) });
    deps.loadPdfjs = async () => { throw new Error('module failed to load'); };
    expect(await read()).toEqual({ error: 'Error: module failed to load' });
  });
});
