/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

// pdfText.test.js — chat/modules/pdfText.js against the BUNDLED pdf.js (chat/libs/pdfjs), the
// exact files the add-on ships, using PDFs generated by test/helpers/pdfFixtures.js.

import { describe, it, expect, vi } from 'vitest';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { buildPdf } from './helpers/pdfFixtures.js';

vi.mock('../agent/modules/utils.js', () => ({ log: vi.fn() }));

const { extractPdfText, hasPdfSignature, PDF_TEXT_OUTCOME } = await import('../chat/modules/pdfText.js');

const LIB_DIR = path.resolve(import.meta.dirname, '../chat/libs/pdfjs');
const pdfjs = await import(pathToFileURL(path.join(LIB_DIR, 'pdf.min.mjs')).href);
pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(path.join(LIB_DIR, 'pdf.worker.min.mjs')).href;
// Node's CMap reader takes a filesystem path.
const cMapUrl = path.join(LIB_DIR, 'cmaps') + path.sep;

const LIMITS = { maxPages: 20, maxOutputChars: 100000, timeoutMs: 20000 };
const extract = (data, range, limits = LIMITS) =>
  extractPdfText(data, { startPage: 1, endPage: null, ...range }, { pdfjs, cMapUrl, limits });
const pageTexts = (result) => result.pages.map((p) => p.text);

describe('hasPdfSignature', () => {
  const bytes = (s) => new TextEncoder().encode(s);

  it('finds the header at the start or after leading junk inside the window', () => {
    expect(hasPdfSignature(bytes('%PDF-1.7\n...'), 1024)).toBe(true);
    expect(hasPdfSignature(bytes('junk junk %PDF-1.4'), 1024)).toBe(true);
  });

  it('rejects files without the header, or with it only past the window', () => {
    expect(hasPdfSignature(bytes('PK\u0003\u0004 a zip file'), 1024)).toBe(false);
    expect(hasPdfSignature(bytes('%PDF'), 1024)).toBe(false);
    expect(hasPdfSignature(bytes('x'.repeat(20) + '%PDF-1.4'), 16)).toBe(false);
    expect(hasPdfSignature(new Uint8Array(0), 1024)).toBe(false);
  });
});

describe('extractPdfText — page ranges', () => {
  const doc = () => buildPdf({ pages: ['Page one text', 'Page two text', 'Page three text', 'Page four text'] });

  it('reads every page by default, with their numbers and the total', async () => {
    const r = await extract(doc());
    expect(r.outcome).toBe(PDF_TEXT_OUTCOME.OK);
    expect(r.totalPages).toBe(4);
    expect([r.firstPage, r.lastPage]).toEqual([1, 4]);
    expect(r.pages.map((p) => p.page)).toEqual([1, 2, 3, 4]);
    expect(pageTexts(r)).toEqual(['Page one text', 'Page two text', 'Page three text', 'Page four text']);
    expect(r.nextStartPage).toBeNull();
  });

  it('reads exactly the requested range and points at the next page', async () => {
    const r = await extract(doc(), { startPage: 2, endPage: 3 });
    expect(pageTexts(r)).toEqual(['Page two text', 'Page three text']);
    expect([r.firstPage, r.lastPage, r.nextStartPage]).toEqual([2, 3, 4]);
  });

  it('clamps an end_page past the document to its last page', async () => {
    const r = await extract(doc(), { startPage: 3, endPage: 99 });
    expect(r.pages.map((p) => p.page)).toEqual([3, 4]);
    expect(r.nextStartPage).toBeNull();
  });

  it('reads at most maxPages pages per call, even when more are requested', async () => {
    const r = await extract(doc(), { startPage: 1, endPage: 4 }, { ...LIMITS, maxPages: 3 });
    expect(r.pages.map((p) => p.page)).toEqual([1, 2, 3]);
    expect(r.nextStartPage).toBe(4);
  });

  it('reports a start page past the end with the page count', async () => {
    const r = await extract(doc(), { startPage: 5 });
    expect(r).toEqual({ outcome: PDF_TEXT_OUTCOME.PAST_END, totalPages: 4 });
  });

  it('keeps line breaks within a page', async () => {
    const r = await extract(buildPdf({ pages: ['First line\nSecond line'] }));
    expect(pageTexts(r)).toEqual(['First line\nSecond line']);
  });
});

describe('extractPdfText — pages without text', () => {
  it('returns empty text for an empty page and an image-only page, not an error', async () => {
    const r = await extract(buildPdf({ pages: ['Has text', null, { image: true }] }));
    expect(r.outcome).toBe(PDF_TEXT_OUTCOME.OK);
    expect(pageTexts(r)).toEqual(['Has text', '', '']);
    expect(r.pages.every((p) => p.unreadable === false)).toBe(true);
  });
});

describe('extractPdfText — CJK text through the bundled CMaps', () => {
  it('decodes a font that uses a predefined CMap', async () => {
    const r = await extract(buildPdf({ pages: [{ cjk: '日本語のテキスト' }] }));
    expect(pageTexts(r)).toEqual(['日本語のテキスト']);
  });
});

describe('extractPdfText — output limit', () => {
  // Lines stay inside the page width: pdf.js drops text that runs off the page.
  const block = (ch, lines) => Array(lines).fill(ch.repeat(30)).join('\n'); // 31 * lines - 1 chars

  it('stops before a page that would overflow the limit and resumes there', async () => {
    const r = await extract(buildPdf({ pages: [block('a', 3), block('b', 3), block('c', 3)] }), {}, { ...LIMITS, maxOutputChars: 200 });
    expect(pageTexts(r)).toEqual([block('a', 3), block('b', 3)]);
    expect(r.stoppedAtOutputLimit).toBe(true);
    expect(r.cutPage).toBeNull();
    expect(r.nextStartPage).toBe(3);
  });

  it('cuts an oversized FIRST page at the limit and moves on, so every call makes progress', async () => {
    const r = await extract(buildPdf({ pages: [block('a', 5), 'next'] }), {}, { ...LIMITS, maxOutputChars: 100 });
    expect(r.pages).toHaveLength(1);
    expect(r.pages[0].text).toBe(block('a', 5).slice(0, 100));
    expect(r.pages[0].cutFrom).toBe(block('a', 5).length);
    expect(r.cutPage).toBe(1);
    expect(r.stoppedAtOutputLimit).toBe(false);
    expect(r.nextStartPage).toBe(2);
  });

  it('never returns more text than the limit', async () => {
    const r = await extract(buildPdf({ pages: [block('x', 2), block('y', 2), block('z', 2)] }), {}, { ...LIMITS, maxOutputChars: 150 });
    const total = r.pages.reduce((n, p) => n + p.text.length, 0);
    expect(total).toBeLessThanOrEqual(150);
    expect(r.pages.map((p) => p.page)).toEqual([1, 2]);
  });
});

describe('extractPdfText — refusals', () => {
  it('classifies a PDF with a user password as encrypted', async () => {
    const r = await extract(buildPdf({ pages: ['Secret'], encrypt: { userPassword: 'pw', ownerPassword: 'owner' } }));
    expect(r).toEqual({ outcome: PDF_TEXT_OUTCOME.ENCRYPTED });
  });

  it('reads a PDF that has only an owner password (no password needed to open it)', async () => {
    const r = await extract(buildPdf({ pages: ['Owner only'], encrypt: { userPassword: '', ownerPassword: 'owner' } }));
    expect(r.outcome).toBe(PDF_TEXT_OUTCOME.OK);
    expect(pageTexts(r)).toEqual(['Owner only']);
  });

  it('classifies garbage, a truncated file and an empty file as malformed', async () => {
    const truncated = buildPdf({ pages: ['abc'] }).slice(0, 40);
    for (const data of [new TextEncoder().encode('%PDF-1.4 not really a pdf'), truncated, new Uint8Array(0)]) {
      expect(await extract(data)).toEqual({ outcome: PDF_TEXT_OUTCOME.MALFORMED });
    }
  });
});

describe('extractPdfText — deadline', () => {
  function stalledPdfjs() {
    const destroy = vi.fn(async () => {});
    return {
      destroy,
      lib: { getDocument: vi.fn(() => ({ promise: new Promise(() => {}), destroy })) },
    };
  }

  it('stops at the deadline and destroys the loading task (terminating its worker)', async () => {
    const { lib, destroy } = stalledPdfjs();
    const r = await extractPdfText(new Uint8Array([1]), { startPage: 1, endPage: null }, { pdfjs: lib, cMapUrl, limits: { ...LIMITS, timeoutMs: 5 } });
    expect(r).toEqual({ outcome: PDF_TEXT_OUTCOME.TIMEOUT });
    expect(destroy).toHaveBeenCalledTimes(1);
  });

  it('destroys the loading task after a successful read too', async () => {
    const destroySpy = vi.spyOn(pdfjs, 'getDocument');
    const r = await extract(buildPdf({ pages: ['ok'] }));
    expect(r.outcome).toBe(PDF_TEXT_OUTCOME.OK);
    const task = destroySpy.mock.results[0].value;
    expect(task.destroyed).toBe(true);
    destroySpy.mockRestore();
  });

  it('passes the text-only safety options to pdf.js', async () => {
    const { lib } = stalledPdfjs();
    await extractPdfText(new Uint8Array([1]), { startPage: 1, endPage: null }, { pdfjs: lib, cMapUrl, limits: { ...LIMITS, timeoutMs: 1 } });
    expect(lib.getDocument).toHaveBeenCalledWith(expect.objectContaining({
      isEvalSupported: false,
      enableXfa: false,
      disableFontFace: true,
      cMapUrl,
      cMapPacked: true,
    }));
  });
});

describe('extractPdfText — a damaged page', () => {
  it('marks the page unreadable and still returns the others', async () => {
    const pages = { 1: 'first', 3: 'third' };
    const doc = {
      numPages: 3,
      getPage: vi.fn(async (n) => {
        if (n === 2) throw Object.assign(new Error('bad page'), { name: 'FormatError' });
        return { getTextContent: async () => ({ items: [{ str: pages[n], hasEOL: false }] }), cleanup: vi.fn() };
      }),
    };
    const lib = { getDocument: () => ({ promise: Promise.resolve(doc), destroy: vi.fn(async () => {}) }) };
    const r = await extractPdfText(new Uint8Array([1]), { startPage: 1, endPage: null }, { pdfjs: lib, cMapUrl, limits: LIMITS });
    expect(r.pages).toEqual([
      { page: 1, text: 'first', unreadable: false },
      { page: 2, text: '', unreadable: true },
      { page: 3, text: 'third', unreadable: false },
    ]);
  });
});

describe('loadBundledPdfjs / bundledCMapUrl', () => {
  it('loads the bundled pdf.js once, pointing it at the bundled worker and CMaps', async () => {
    const { loadBundledPdfjs, bundledCMapUrl } = await import('../chat/modules/pdfText.js');
    globalThis.browser = { runtime: { getURL: (p) => `moz-extension://test/${p}` } };
    // The loader may share this file's pdf.js instance; keep the real worker for other tests.
    const realWorkerSrc = pdfjs.GlobalWorkerOptions.workerSrc;
    try {
      const first = await loadBundledPdfjs();
      expect(await loadBundledPdfjs()).toBe(first);
      expect(typeof first.getDocument).toBe('function');
      expect(first.GlobalWorkerOptions.workerSrc).toBe('moz-extension://test/chat/libs/pdfjs/pdf.worker.min.mjs');
      expect(bundledCMapUrl()).toBe('moz-extension://test/chat/libs/pdfjs/cmaps/');
    } finally {
      delete globalThis.browser;
      pdfjs.GlobalWorkerOptions.workerSrc = realWorkerSrc;
    }
  });
});

describe('extractPdfText — edge cases', () => {
  const fakeLib = (doc, destroy = vi.fn(async () => {})) => ({ getDocument: () => ({ promise: Promise.resolve(doc), destroy }) });

  it('treats a document that reports no pages as malformed', async () => {
    const r = await extractPdfText(new Uint8Array([1]), { startPage: 1, endPage: null }, { pdfjs: fakeLib({ numPages: 0 }), cMapUrl, limits: LIMITS });
    expect(r).toEqual({ outcome: PDF_TEXT_OUTCOME.MALFORMED });
  });

  it('still returns the result when destroying the task fails', async () => {
    const doc = { numPages: 1, getPage: async () => ({ getTextContent: async () => ({ items: [{ str: 'ok' }] }), cleanup() {} }) };
    const r = await extractPdfText(new Uint8Array([1]), { startPage: 1, endPage: null }, {
      pdfjs: fakeLib(doc, vi.fn(async () => { throw new Error('already gone'); })), cMapUrl, limits: LIMITS,
    });
    expect(r.pages).toEqual([{ page: 1, text: 'ok', unreadable: false }]);
  });

  it('does not split a surrogate pair when cutting a page at the limit', async () => {
    const text = 'ab' + '😀'.repeat(5); // the 4th UTF-16 unit is the second half of the first emoji
    const doc = { numPages: 1, getPage: async () => ({ getTextContent: async () => ({ items: [{ str: text }] }), cleanup() {} }) };
    const r = await extractPdfText(new Uint8Array([1]), { startPage: 1, endPage: null }, { pdfjs: fakeLib(doc), cMapUrl, limits: { ...LIMITS, maxOutputChars: 3 } });
    expect(r.pages[0].text).toBe('ab');
  });
});
