/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import { formatTimestampForAgent } from "../../chat/modules/helpers.js";
import { accountIdOfMsgId, getAttachmentRepairedAccounts } from "../../fts/attachmentFlags.js";
import { ACTIONS, getActionForWeId } from "./actionCache.js";
import { SETTINGS } from "./config.js";
import { isInboxFolder } from "./folderUtils.js";
import { getSummary } from "./summaryGenerator.js";
import { getUniqueMessageKey, log } from "./utils.js";

// NOTE: isInboxFolder moved to folderUtils.js to avoid circular dependencies.

/**
 * Get the total count of messages in all inboxes
 * @returns {Promise<number>} Total count of inbox messages across all accounts
 */
export async function getTotalInboxCount() {
  let totalCount = 0;
  
  try {
    const accounts = await browser.accounts.list();
    
    for (const acc of accounts) {
      try {
        if (!acc.rootFolder) continue;
        
        const inboxFolder = await getInboxForAccount(acc.id);
        if (!inboxFolder) continue;
        
        // Paginate to count all messages
        let page = await browser.messages.list(inboxFolder.id);
        while (page && page.messages && page.messages.length > 0) {
          totalCount += page.messages.length;
          if (page.id) {
            page = await browser.messages.continueList(page.id);
          } else {
            break;
          }
        }
      } catch (e) {
        log(`[InboxContext] Error counting messages for account ${acc.name}: ${e}`, "warn");
      }
    }
  } catch (e) {
    log(`[InboxContext] Error getting total inbox count: ${e}`, "error");
  }
  
  log(`[InboxContext] Total inbox count: ${totalCount}`, 'debug');
  return totalCount;
}

/**
 * Get the inbox folder for a given account
 */
export async function getInboxForAccount(accountId) {
  try {
    const accounts = await browser.accounts.list();
    const account = accounts.find(acc => acc.id === accountId);
    
    if (!account?.rootFolder) {
      log(`[InboxLookup] No root folder for account ${accountId}`, 'debug');
      return null;
    }
    
    const subFolders = await browser.folders.getSubFolders(account.rootFolder.id, true);
    const allFolders = [account.rootFolder, ...subFolders];
    
    // Find the inbox folder
    const inbox = allFolders.find(f => isInboxFolder(f));
    
    if (inbox) {
      log(`[InboxLookup] Found inbox for account ${accountId}: '${inbox.name}' (path='${inbox.path}')`, 'debug');
    } else {
      log(`[InboxLookup] No inbox found for account ${accountId}`, "warn");
    }
    
    return inbox;
  } catch (e) {
    log(`[InboxLookup] Error finding inbox for account ${accountId}: ${e}`, "error");
    return null;
  }
}

/**
 * Builds the full inbox context as an *array* of objects, then returns the
 * JSON string representation. The caller can JSON.parse if a JS object is
 * required.
 *
 * Each entry has the following shape:
 *   {
 *     uniqueId: string,          // Globally-unique message key (folderUri:headerID)
 *     internalId: number,        // Thunderbird internal numeric message id (fast look-ups)
 *     subject: string,
 *     from: string,              // "Author" field (name <email>)
 *     blurb: string,             // One–line summary generated by LLM
 *     todos: string,             // Extracted action items (only included for action="reply")
 *     action: string             // One of "delete" | "archive" | "reply" | "" (empty if none)
 *     date: string               // Localized date string (e.g., MM/DD/YY)
 *     hasAttachments: boolean|null // Whether the email has attachments; null = unknown
 *     replied: boolean           // Whether the email has been replied to
 *   }
 *
 * Heavy LLM calls (summary generation) are throttled by summary.js & llm.js
 * semaphores, so we simply launch them in parallel here.
 */
export async function buildInboxContext() {
  const contextArray = [];
  const allMessages = []; // Collect all messages for bulk replied status check
  const maxEmails = SETTINGS.inboxManagement?.maxRecentEmails || 100;
  
  try {
    const accounts = await browser.accounts.list();

    for (const acc of accounts) {
      try {
        if (!acc.rootFolder) continue;

        // Use centralized inbox lookup
        const inboxFolder = await getInboxForAccount(acc.id);
        if (!inboxFolder) {
          continue;
        }

        // Paginate through message list to fetch all messages
        let page = await browser.messages.list(inboxFolder.id);
        while (page && page.messages && page.messages.length > 0) {
          for (const msg of page.messages) {
            allMessages.push(msg);
          }
          if (page.id) {
            page = await browser.messages.continueList(page.id);
          } else {
            break;
          }
        }
      } catch (subErr) {
        // log(`[TMDBG InboxContext] Error traversing account ${acc.name}: ${subErr}`);
      }
    }

    log(`[InboxContext] Collected ${allMessages.length} total inbox messages`, 'debug');

    // Sort all messages by date descending (most recent first)
    allMessages.sort((a, b) => {
      const dateA = a.date ? new Date(a.date).getTime() : 0;
      const dateB = b.date ? new Date(b.date).getTime() : 0;
      return dateB - dateA;
    });

    // Limit to most recent maxEmails
    const messagesToProcess = allMessages.slice(0, maxEmails);
    
    if (allMessages.length > maxEmails) {
      log(`[InboxContext] Inbox has ${allMessages.length} messages, limiting context to most recent ${maxEmails}`, 'debug');
    }

    // Process only the limited set of messages
    // Use Promise.all with indexed entries to maintain order
    const summaryPromises = messagesToProcess.map((msg, idx) => 
      _createContextEntry(msg).then(entry => ({ idx, entry }))
    );

    const results = await Promise.all(summaryPromises);
    
    // Sort by index to maintain original order, then extract entries
    results.sort((a, b) => a.idx - b.idx);
    for (const { entry } of results) {
      if (entry) {
        contextArray.push(entry);
      }
    }

    // Bulk fetch replied status and HasRe flag for processed messages only
    try {
      const messageIds = messagesToProcess.map(msg => msg.id);

      const [repliedStatuses, hasReStatuses, hasAttachmentStatuses] = await Promise.all([
        _getRepliedStatusBulk(messagesToProcess),
        browser.tmHdr.getHasReBulk(messageIds).catch(e => {
          log(`[InboxContext] getHasReBulk failed: ${e}`, "warn");
          return [];
        }),
        _getAttachmentFlags(contextArray),
      ]);

      // The bulk results follow messagesToProcess; contextArray skips messages whose entry failed.
      const indexById = new Map(messagesToProcess.map((msg, i) => [msg.id, i]));

      // Update contextArray with replied status, attachment flag and restore "Re:" prefix
      contextArray.forEach((entry, j) => {
        const i = indexById.get(entry.internalId);
        entry.replied = repliedStatuses[i] || false;
        // true / false, or null when it could not be read ("unknown", never "no").
        entry.hasAttachments = hasAttachmentStatuses[j];
        // TB strips "Re:" from MessageHeader.subject — restore it using HasRe flag
        if (hasReStatuses[i] && entry.subject && !entry.subject.startsWith("Re: ")) {
          entry.subject = "Re: " + entry.subject;
        }
      });

      log(`[InboxContext] Successfully fetched replied status for ${contextArray.length} messages`, 'debug');
    } catch (e) {
      log(`[InboxContext] Failed to fetch replied status: ${e}`, "error");
      // Set all to false if bulk fetch fails
      for (let i = 0; i < contextArray.length; i++) {
        contextArray[i].replied = false;
      }
    }
  } catch (e) {
    // log(`[TMDBG InboxContext] Failed to build inbox context: ${e}`, "error");
  }

  return JSON.stringify(contextArray);
}

async function _createContextEntry(msgHeader) {
  try {
    // Determine current action from the IDB action cache.
    const cached = await getActionForWeId(msgHeader);
    const action =
      cached === ACTIONS.DELETE || cached === ACTIONS.ARCHIVE || cached === ACTIONS.REPLY
        ? cached
        : "";

    // Fetch (or generate) summary blurb and todos
    let detailed = "";
    let blurb = "";
    let todos = "";
    try {
      const summaryObj = await getSummary(msgHeader, false, true); // cache only
      detailed = summaryObj?.detailed || "";
      blurb = summaryObj?.blurb || "";
      // Only include todos for emails marked as "reply"
      todos = (action === "reply") ? (summaryObj?.todos || "") : "";
    } catch (e) {
      // log(`[TMDBG InboxContext] Summary failed for message ${msgHeader.id}: ${e}`);
    }

    // Convert date using unified agent timestamp formatting for consistency.
    let dateStr = "";
    try {
      if (msgHeader.date) {
        const d = new Date(msgHeader.date);
        dateStr = formatTimestampForAgent(d);
      }
    } catch (_) { /* ignore formatting errors */ }

    // Generate unique ID using centralized function
    const uniqueId = await getUniqueMessageKey(msgHeader);

    return {
      uniqueId: uniqueId || "",
      internalId: msgHeader.id,
      headerMessageId: msgHeader.headerMessageId || "",
      subject: msgHeader.subject || "",
      from: msgHeader.author || "",
      detailed,
      blurb,
      todos,
      action,
      date: dateStr,
      hasAttachments: null, // Will be updated by bulk fetch
      replied: false, // Will be updated by bulk fetch
    };
  } catch (e) {
    // log(`[TMDBG InboxContext] Error processing message ${msgHeader?.id}: ${e}`);
    return null;
  }
}

// Thunderbird's MessageHeader has no attachment field. The index's flag comes from the downloaded
// message and is trusted for accounts whose old rows were repaired (fts/attachmentFlags.js), as in
// email_search. Emails of other accounts, emails not indexed yet, and a failed index read take
// Thunderbird's database flag (the paperclip heuristic). In entry order: true / false, or null
// when neither could tell ("unknown", never "no").
async function _getAttachmentFlags(entries) {
  const flags = entries.map(() => null);
  let repaired = new Set();
  try {
    repaired = await getAttachmentRepairedAccounts();
  } catch (e) {
    log(`[InboxContext] reading the repaired accounts failed: ${e}`, "error");
  }
  const fromIndex = [];
  entries.forEach((entry, i) => {
    if (entry.uniqueId && repaired.has(accountIdOfMsgId(entry.uniqueId))) fromIndex.push(i);
  });
  if (fromIndex.length > 0) {
    try {
      const msgIds = fromIndex.map(i => entries[i].uniqueId);
      const { ftsSearch, isFtsEngineInitialized } = await import("../../fts/engine.js");
      // Only the background owns the helper; the chat window asks it.
      const res = isFtsEngineInitialized()
        ? await ftsSearch.getAttachmentFlags(msgIds)
        : await browser.runtime.sendMessage({ type: "fts", cmd: "getAttachmentFlags", msgIds });
      if (!Array.isArray(res?.flags)) throw new Error(res?.error || "no flags in the response");
      fromIndex.forEach((entryIdx, k) => {
        if (typeof res?.flags?.[k] === "boolean") flags[entryIdx] = res.flags[k];
      });
    } catch (e) {
      log(`[InboxContext] index attachment flags failed: ${e}`, "warn");
    }
  }
  const fromThunderbird = [];
  flags.forEach((flag, i) => { if (flag === null) fromThunderbird.push(i); });
  log(`[InboxContext] attachment flags: ${entries.length - fromThunderbird.length} from the index, ${fromThunderbird.length} from Thunderbird`, 'debug');
  if (fromThunderbird.length > 0) {
    try {
      const statuses = await browser.tmHdr.getHasAttachmentBulk(fromThunderbird.map(i => entries[i].internalId));
      fromThunderbird.forEach((entryIdx, k) => {
        if (typeof statuses[k] === "boolean") flags[entryIdx] = statuses[k];
      });
    } catch (e) {
      log(`[InboxContext] getHasAttachmentBulk failed: ${e}`, "error");
    }
  }
  return flags;
}

/**
 * Bulk fetch replied status for all messages using tmHdr experiment
 * @param {Array} messages - Array of message headers
 * @returns {Promise<Array<boolean>>} - Array of replied status for each message
 */
async function _getRepliedStatusBulk(messages) {
  try {
    if (!messages || messages.length === 0) {
      return [];
    }

    // Replied flags are read by WebExtension message id.
    const items = messages.map(msg => msg.id);

    log(`[InboxContext] Calling tmHdr.getRepliedBulk for ${items.length} messages`, 'debug');
    
    // Call the bulk API
    const results = await browser.tmHdr.getRepliedBulk(items);
    
    log(`[InboxContext] tmHdr.getRepliedBulk returned ${results.length} results`, 'debug');
    
    // Log summary of results
    const trueCount = results.filter(r => r === true).length;
    const falseCount = results.filter(r => r === false).length;
    log(`[InboxContext] Replied status: ${trueCount} true, ${falseCount} false out of ${results.length} total`, 'debug');
    
    // Log first few results for debugging
    for (let i = 0; i < Math.min(5, results.length); i++) {
      log(`[InboxContext] Result[${i}]: ${results[i]} (subject: "${messages[i]?.subject}")`, 'debug');
    }
    
    return results;
  } catch (e) {
    log(`[InboxContext] Error in _getRepliedStatusBulk: ${e}`, "error");
    // Return array of false values on error
    return new Array(messages.length).fill(false);
  }
} 